---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1 
kind: Job
metadata:
  name: "jmeter-job"
spec:
  template:
    metadata:
      labels:
        app: "jmeter"
    spec:
      restartPolicy: "Never"
      containers:
      - image: "xlight05/volume-test:latest"
        name: "jmeter-job"
        volumeMounts:
        - mountPath: "/results"
          name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
---
