name: Benchmark github hook.
on:
  repository_dispatch:
    types: [perf]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prints payload
      run: |
    

        result1="{{ github.event.client_payload.result }}"
        echo $result1
        
        results="join(${{ github.event.client_payload.result }}, ',')"
        echo $results