name: Docker Build Test

on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker ps
        run: |
          docker ps
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@nightly
        env:
          CI_BUILD: true
          WORKING_DIR: load-tests/ballerina_hello/src
        with:
          args:
            build
