name: test_workflow

on:
  workflow_dispatch:
    inputs:
      dispatchType:
        description: 'Repository dispatch type'
        default: ''
        required: false
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test 1
      if: github.event.inputs.dispatchType != ''
      run: |
        echo "Did it skip?"
    - name: Test 2
      run: |
        echo "This is gonna exec anyways"